# Database configuration now loaded from AWS Systems Manager Parameter Store
# 
# Parameters are expected to be stored under the following paths:
# /bikestore/development/database/adapter
# /bikestore/development/database/database
# /bikestore/development/database/pool
# /bikestore/development/database/timeout
# 
# /bikestore/test/database/adapter
# /bikestore/test/database/database
# /bikestore/test/database/pool
# /bikestore/test/database/timeout
# 
# /bikestore/production/database/adapter
# /bikestore/production/database/database
# /bikestore/production/database/pool
# /bikestore/production/database/timeout
# /bikestore/production/database/host
# /bikestore/production/database/username
# /bikestore/production/database/password
#
# For PostgreSQL/MySQL, additional parameters like host, username, password can be added

<%= 
  require_relative 'database'
  DatabaseConfig.load_config.to_yaml.sub(/^---\n/, '')
%>